package utils

const USER_REGISTERED_MESSAGE = "USER REGISTERED\n"
const USER_ALREADY_EXISTS_MESSAGE = "USER ALREADY_EXISTS\n"
const USER_DOES_NOT_EXISTS_MESSAGE = "USER DOES_NOT_EXISTS\n"
const USER_LOGGED_MESSAGE = "USER LOGGED\n"
const LOG_IN_FIRST_MESSAGE = "LOG IN FIRST\n"
const USER_LOGGED_OUT_MESSAGE = "USER LOGGED OUT\n"
const ROOM_CREATED_SUCCESS_MESSAGE = "ROOM CREATED SUCCESS\n"
const ROOM_ALREADY_EXISTS_MESSAGE = "ROOM ALREADY EXISTS\n"
const ROOM_PASSWORD_NOT_PROVIDED_MESSAGE = "ROOM PASSWORD_NOT_PROVIDED\n"
const INVALID_ROOM_ARGUMENTS_MESSAGE = "INVALID_ROOM_ARGUMENTS\n"
const ROOM_DOES_NOT_EXISTS_MESSAGE = "ROOM DOES_NOT_EXISTS\n"
const USER_INSERTED_INTO_ROOM_MESSAGE = "USER INSERTED INTO_ROOM\n"
