package utils

const USER_REGISTERED_MESSAGE = "USER REGISTERED"
const USER_ALREADY_EXISTS_MESSAGE = "USER ALREADY_EXISTS"
const USER_DOES_NOT_EXISTS_MESSAGE = "USER DOES_NOT_EXISTS"
const USER_LOGGED_MESSAGE = "USER LOGGED"
const LOG_IN_FIRST_MESSAGE = "LOG IN FIRST"
const USER_LOGGED_OUT_MESSAGE = "USER LOGGED OUT"
const ROOM_CREATED_SUCCESS_MESSAGE = "ROOM CREATED SUCCESS"
const ROOM_ALREADY_EXISTS_MESSAGE = "ROOM ALREADY EXISTS"
const ROOM_PASSWORD_NOT_PROVIDED_MESSAGE = "ROOM PASSWORD_NOT_PROVIDED"
const INVALID_ROOM_ARGUMENTS_MESSAGE = "INVALID_ROOM_ARGUMENTS"
const ROOM_DOES_NOT_EXISTS_MESSAGE = "ROOM DOES_NOT_EXISTS"
const USER_INSERTED_INTO_ROOM_MESSAGE = "USER INSERTED INTO_ROOM"
